services:
  game-engine:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - game_engine_node_modules:/app/node_modules
    ports:
      - "3000:3000"

  install-host:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["npm"]
    command: ["install"]
    profiles: ["install-host"]

volumes:
  game_engine_node_modules:
